version: "3.8"

services:
  api:
    build:
      context: ./backend
    container_name: fastapi-app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  firebase-emulator:
    image: andreysenov/firebase-tools
    container_name: firebase-emulator
    ports:
      - "9099:9099" # Auth Emulator
      - "8080:8080" # Firestore Emulator
      - "4000:4000" # Emulator Suite UI
    volumes:
      - ./firebase:/app/firebase
    working_dir: /app
    command: firebase emulators:start --project demo-project
